# title of website
title: AY

# description of website
# description: ximm12a's navigation site

# favicon of website
favicon: "https://github.com/ximm12a.png?size=40"

# your website url
url: https://ximm12a.github.io/yi/

# github profile url
github: "https://github.com/ximm12a"

# footer message
# footer: © 2023 @ximm12a

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"



content:
  categories:
    - name: 常用推荐
      sites:
        - name: Google
          description: google
          url: https://www.google.com/
        - name: inoreader
          description: rss
          url: https://www.inoreader.com/
        - name: chatGPT
          description: chatGPT
          url: https://chat.openai.com/chat
        - name: Notion
          description: Notion
          url: https://www.notion.so/
        - name: 今日热榜官网
          description: 热榜
          url: https://tophub.today/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 雪球行情
          description: 行情
          url: https://xueqiu.com/hq


    - name: 娱乐
      sites:
        - name: YouTube
          description: 
          url: https://www.youtube.com/
        - name: 哔哩哔哩 bilibili
          description: 
          url: https://www.bilibili.com/
        - name: 抖音
          description: 
          url: https://www.douyin.com/
        - name: Twitter
          description: 
          url: https://twitter.com/

        - name: 看片狂人
          description: 
          url: https://www.kpkuang.fun/
        - name: 电影天堂
          description: 
          url: https://www.dy2018.com/
        - name: 茶杯狐
          description: 
          url: https://cupfox.app/
        - name: 低端影视 - 超清在线视频站
          description: 
          url: https://ddys.art/



    - name: ACG
      sites:
        - name: 最新动漫之家
          description: 
          url: https://manhua.dmzj.com/update_1.shtml
        - name: 最新看漫画
          description: 
          url: https://www.manhuagui.com/update/
        - name: mx 动画在线
          description: 
          url: http://www.mxdm8.com/
        - name: Bangumi 番组计划
          description: 
          url: https://bgm.tv/
        - name: 蜜柑计划
          description: 动画下载
          url: https://mikanani.me/
        - name: 漫展时间表
          description: 
          url: https://www.nyato.com/manzhan/p440100
        - name: Switch520
          description: 动画下载
          url: https://xxxxx525.com/
        - name: 游戏天堂
          description: 
          url: https://www.zzzz688.com/




    - name: 网盘 邮箱 工具 
      sites:
        - name: 百度网盘
          description: 
          url: https://pan.baidu.com
        - name: 阿里云盘
          description: 
          url: https://www.aliyundrive.com
        - name: Gmail
          description: 
          url: https://mail.google.com
        - name: QQ邮箱
          description: 
          url: https://mail.qq.com/

        - name: Z-Library Project
          description: 
          url: https://singlelogin.me/
        - name: DeepL翻译
          description: 
          url: https://www.deepl.com/translator
        - name: Startpage
          description: 搜索
          url: https://www.startpage.com/
